name: multi_image_crop
description: A flutter package to crop multiple images at a time on iOS and Android.
version: 0.0.1
homepage: https://github.com/tejbhansahu/multi_image_crop

environment:
  sdk: ">=2.16.2 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  image_crop: ^0.4.0
  preload_page_view: ^0.1.6
  scroll_to_index: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
